### ISSUE TITLE
Log Module name and filter specs for each loaded module once

### ISSUE THREAD

**Issue by sweisgerber-dev** [Project-ARTist/ARTist#21]
I think it could be really helpful if we would log loaded ARTist module names and their filter spec once,
when ARTist loads a module.

## Example

```
HArtist() Version: 00112 Module: `<MODULE-NAME>`
# Filters:
- `com.android.server.AppOpsService`
- `com.android.server.`
- `...`
# Injections:
- Method: `Lsaarland/cispa/artist/codelib/CodeLib;traceLog()V`
    - Targets:
        - METHOD_START: "GENERIC_TARGET"
        - METHOD_CALL_BEFORE: "onTransact("
- Method: `Lsaarland/cispa/artist/codelib/CodeLib;traceLog2()V`
    - Targets:
        - METHOD_CALL_BEFORE: "onCreate("
```

## Helpful files/methods

- `compiler/optimizing/artist/artist.cc`
    - `void HArtist::LogVersionOnce(const string& VERSION)`
- `Module::getMethodFilter()`
- `HUniversalArtist::ProvideInjections`
